name: 02 - Workflow Events

on:
  push:
    branches: [ master ]
  pull_request:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Event name
        run: |
          echo "Event name: ${{ github.event_name }}"