name: 05 - 2 - Event Filters and Activity Types

on:
    # pull_request:
    #     types:
    #         - closed
    #     branches:
    #         - master
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Run on Closed PR
              run: |
                echo "Running whenever a PR is closed"
        