name: 06 - Contexts

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
    # - push
    workflow_dispatch:
        # inputs:
        #     debug:
        #         type: boolean
        #         default: true

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: 'job'
        steps:
            - name: Display Information
              run: |
                echo "This is the repository owner: ${{ github.repository_owner }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{  github.sha }}"
                echo "Actor: ${{ github.actor_id}}"
                echo "Workflow: ${{ github.workflow }}"
                # echo "Workflow Name: $(basename $GITHUB_WORKFLOW_PATH .yml) >> echo $GITHUB_ENV"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number}}"
                echo "Repository: ${{ github.repository }} on branch: $(basename ${{ github.ref }})"

            - name: Retrieve Variable
              run: |
                echo "${{ vars.MY_VAR }}"

            - name: Print Env Variables - 1st
              run: |
                echo "Workflow env: $MY_WORKFLOW_VAR"
                echo "Overwritten env: $MY_OVERWRITTEN_VAR"

            - name: Print Env Variables - 2nd
              run: |
                echo "Workflow env: $MY_WORKFLOW_VAR"
                echo "Overwritten env: $MY_OVERWRITTEN_VAR"
