name: 06 - Contexts

on:
    - push
    - workflow_dispatch

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "This is the repository owner: ${{ github.repository_owner }}"
                echo "Event name: ${{ github.event }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{  github.sha }}"
                echo "Actor: ${{ github.actor_id}}"
                echo "Workflow: ${{ github.workflow.name }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number}}"
                echo "Repository: ${{ github.repository }} on branch ${{  github.head_ref }}"

            - name: Retrieve Variable
              env:
                MY_VAR: ${{ env.MY_VAR }}
              run: |
                echo "$MY_VAR"
