# name: 06 - Contexts

run-name: My custom workflow run name - ${{ runner.os }}

on:
    - push
    - workflow_dispatch

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "This is the repository owner: ${{ github.repository_owner }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{  github.sha }}"
                echo "Actor: ${{ github.actor_id}}"
                echo "Workflow: ${{ github.workflow }}"
                # echo "Workflow Name: $(basename $GITHUB_WORKFLOW_PATH .yml) >> echo $GITHUB_ENV"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number}}"
                echo "Repository: ${{ github.repository }} on branch: $(basename ${{ github.ref }})"

            - name: Retrieve Variable
              run: |
                echo "${{ vars.MY_VAR }}"
