name: 07 - Using Expressions

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug }}

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print start-up data
              if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }}
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: $(basename ${{ github.ref }})"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ Runner.OS}}"

            - name: Print when triggered from master
              if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }} && $(basename ${{ github.ref }}) == 'master'
              run: |
                echo "I was triggered from $(basename ${{ github.ref }})"

