name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - if : ${{ inputs.debug == 'true' }}
              name: [debug] Print start-up data
              runs: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ .github.sha }}"
                echo "Runner OS: ${{ Runner.OS}}"

            - if : ${{ inputs.debug == 'true' }} && ${{ github.branch == 'master'}}
              name: [debug] Print when triggered from main
              runs: |
                echo ""I was triggered from ${{ github.branch}}

