name: 15 - Working with Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os}}-${{ matrix.node-version }}
        strategy:
            fail-fast: true
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version:  ${{ matrix.node-version }}

            - name: Fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1
            
            - name: Perform some tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                sleep 10

            - name: Upload test results
              run: echo "Uploading test results"

    include-example:
        runs-on: ubuntu-latest
        # env:
        #     matrix-name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
        name: "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
        strategy:
            fail-fast: false
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                    - color: red
                      opacity: 75
                    - shape: circle
                      opacity: 100
                    - color: red
                      shape: triangle
                    - opacity: 50             
        steps:
            - name: Dummey Step
              run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
            
