name: 17 - 1 - Custom Actions - Composite

run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options: [dev, prod]
                description: Select the environment to deploy

env:
    working-directory: '17-custom-actions/react-app'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                path: ${{ env.working-directory  }}/node_modules
                key: node-modules-${{ hashFiles('${{ env.working-directory }}/package-lock.json') }}

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build


