name: 18 - 3 - Reusable Workflows

on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflow.yaml
        with:
            target-directory: random-dir

    e2e-tests:
        uses: maziz00/github-actions-e2e/.github/workflows/e2e.yaml@master
        secrets:
            access-token: ${{ secrets.GH_TOKEN }}