name: 19 - 1 - Managing Concurrency


on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow.name }}-${{github.ref }}

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: https://exaABC123mple.com
                max_trials: '20'
                delay: '5'